# Generated by Django 5.2.7 on 2025-10-11 09:02

import polls.utilities
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0002_choisedquestions'),
    ]

    operations = [
        migrations.AlterField(
            model_name='poluser',
            name='avatar',
            field=models.ImageField(blank=True, upload_to=polls.utilities.get_timstamp_path, verbose_name='Аватар'),
        ),
    ]
