# Generated by Django 5.2.7 on 2025-10-12 12:24

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0003_alter_poluser_avatar'),
    ]

    operations = [
        migrations.AlterField(
            model_name='choisedquestions',
            name='question',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='polls.question', unique=True),
        ),
        migrations.AlterField(
            model_name='choisedquestions',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, unique=True),
        ),
    ]
