# Generated by Django 5.2.7 on 2025-10-20 09:11

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0005_alter_choisedquestions_question_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='expiration_time',
            field=models.DateTimeField(default=datetime.datetime(2025, 10, 22, 9, 11, 42, 449829, tzinfo=datetime.timezone.utc), verbose_name='expiration date'),
        ),
        migrations.AlterField(
            model_name='question',
            name='pub_date',
            field=models.DateTimeField(default=datetime.datetime(2025, 10, 20, 9, 11, 42, 449796, tzinfo=datetime.timezone.utc), verbose_name='date published'),
        ),
    ]
