# Generated by Django 5.2.7 on 2025-10-21 04:11

import datetime
import polls.utilities
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0006_question_expiration_time_alter_question_pub_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='description',
            field=models.TextField(default='', max_length=650, verbose_name='description'),
        ),
        migrations.AddField(
            model_name='question',
            name='image',
            field=models.ImageField(blank=True, default=None, upload_to=polls.utilities.get_timstamp_path, verbose_name='Аватар'),
        ),
        migrations.AddField(
            model_name='question',
            name='short_description',
            field=models.CharField(default='', max_length=50, verbose_name='short_description'),
        ),
        migrations.AlterField(
            model_name='question',
            name='expiration_time',
            field=models.DateTimeField(default=datetime.datetime(2025, 10, 23, 4, 11, 34, 164203, tzinfo=datetime.timezone.utc), verbose_name='expiration date'),
        ),
        migrations.AlterField(
            model_name='question',
            name='pub_date',
            field=models.DateTimeField(default=datetime.datetime(2025, 10, 21, 4, 11, 34, 164172, tzinfo=datetime.timezone.utc), verbose_name='date published'),
        ),
    ]
